### ISSUE TITLE
[BUG] Reading constraints causes `validation` to fail.

### ISSUE THREAD

**Issue by getaddrinfo** [bufbuild/protovalidate-java#12]
## Description
When validating a message, reading a message field that has a constraint on it causes the generated protobuf code to raise a `java.lang.IllegalArgumentException`.

## Steps to Reproduce

1. Create a message with a constraint added to it, e.g.,
```proto
package something;

message Something {
    string name = 1 [(buf.validate.field).string.min_len = 1];
}
```
2. Attempt to validate an instance of the message (example in Kotlin):
```kt
import build.buf.protovalidate.Validator;
import build.buf.protovalidate.exceptions.ValidationException

// ...

val validator = Validator()

val message = Something.newBuilder()
    .setName("something")
    .build();

try {
    val result = validator.validate(request)

    if (result.violations.isEmpty()) {
       println("OK: no validation failures")
    } else {
       println("FAIL: validation failures: " + result.toString())
    }
} catch(ex: ValidatorException) {
    println("exception: " + ex.toString())
}
```

## Expected Behavior

The protobuf message should correctly parse constraints, and validate the message.

## Actual Behavior

The validator fails reading the message definitions. 

## Screenshots/Logs

When running the validator, the following exception is raised:

```java
java.lang.IllegalArgumentException: mergeFrom(Message) can only merge messages of the same type.
        at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:375)
        at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:370)
        at build.buf.gen.buf.validate.FieldConstraints$Builder.mergeFrom(FieldConstraints.java:1829)
        at build.buf.gen.buf.validate.FieldConstraints$Builder.mergeFrom(FieldConstraints.java:1539)
        at com.google.protobuf.GeneratedMessage$GeneratedExtension.singularFromReflectionType(GeneratedMessage.java:1801)
        at com.google.protobuf.GeneratedMessage$GeneratedExtension.fromReflectionType(GeneratedMessage.java:1785)
        at com.google.protobuf.GeneratedMessageV3$ExtendableMessage.getExtension(GeneratedMessageV3.java:1132)
        at com.google.protobuf.GeneratedMessageV3$ExtendableMessage.getExtension(GeneratedMessageV3.java:1199)
        at build.buf.protovalidate.internal.evaluator.ConstraintResolver.resolveFieldConstraints(ConstraintResolver.java:73)
        at build.buf.protovalidate.internal.evaluator.EvaluatorBuilder.processFields(EvaluatorBuilder.java:156)
        at build.buf.protovalidate.internal.evaluator.EvaluatorBuilder.buildMessage(EvaluatorBuilder.java:113)
        at build.buf.protovalidate.internal.evaluator.EvaluatorBuilder.build(EvaluatorBuilder.java:98)
        at build.buf.protovalidate.internal.evaluator.EvaluatorBuilder.loadOrBuildDescriptor(EvaluatorBuilder.java:384)
        at build.buf.protovalidate.internal.evaluator.EvaluatorBuilder.load(EvaluatorBuilder.java:83)
        at build.buf.protovalidate.Validator.validate(Validator.java:76)
        at my.code.rpc.server.Service.someMethod(Service.kt:52)
```

## Environment

- **Operating System**: macOS
- **Version**: macOS 12.6.8 (Monterey) 
- **Compiler/Toolchain**: 
- **Protobuf Compiler & Version**:  
  - `protoc`: `com.google.protobuf:protoc:3.23.4`
  - `grpc`: `io.grpc.protoc-gen-grpc-java:1.56.1`
  - `grpckt`: `io.grpc.protoc-gen-grpc-kotlin:1.3.0:jdk8@jar`
  - `libprotoc`: `3.21.12` (not sure if this is applicable)
- **Protovalidate Version**:`protovalidate-java`: `0.0.1`

## Possible Solution

`ConstraintResolver.resolveFieldConstraints` appears to correctly determine that the field has an annotation that is relevant to `protovalidate`: `options.hasExtension(ValidateProto.field)` evaluates as `true`.

The exception is raised when `options.getExtension(ValidateProto.field)` is called. 

## Additional Context

We are using this library in the context of a GRPC server, written in Kotlin.

**Comment by getaddrinfo** [comment]
This seems to be resolved by #13
